services:
  impress-db:
    image: postgres:11.15-alpine
    container_name: impress-db
    hostname: impress-db
    restart: always
    environment:
      - POSTGRES_USER=uryonym
      - POSTGRES_PASSWORD=uryonym
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - PGTZ=Asia/Tokyo
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - impress-db-volume:/var/lib/postgresql/data

volumes:
  impress-db-volume:
    name: impress-db-volume
    driver: local

